export const menu = [
  {
    name: "Burrata",
    description:
      "podloga od mliječnih mandlih salata, polu sušene cherry rajčice, perlice aceto balsamica, pesto od suhih rajčica, svježi bosiljak",
    price: "9.70 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Pašteta od pileće i gušće jetre s tartufima",
    description: "maslac, džem od luka, toplo brioche pecivo",
    price: "7.90 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Grillani sir škripavac",
    description:
      "džem od brusnice, pikantne crvene papričice, džem od luka, toplo brioche pecivo",
    price: "8.90 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Beef tartar",
    description: "maslac, toplo brioche pecivo, pikantne crvene papričice, pikantni umak",
    price: "9.90 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Mazalica",
    description: "2 kom / 6 kom zapečena mijevena junetina na kriškama lepinje, luk",
    price: "1.30 € / 7.50 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Dimljena pačja prsa",
    description:
      "džem od luka, pikantne crvene papričice, džem od brusnice, toplo brioche pecivo",
    price: "9.90 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Pohana paprika punjena sirom",
    description:
      "pečena crvena paprika punjena selekcijom sira, panko mrvice, tartar umak",
    price: "8.90 €",
    category: "početak",
    sub_category: "hladna predjela",
  },
  {
    name: "Domaća goveđa juha",
    description: "domaći rezanci i mrkva",
    price: "3.90 €",
    category: "početak",
    sub_category: "juhe",
  },
  {
    name: "Gusta juha od rajčice s krutonima",
    description: "gusta juha od rajčica, krutoni, svježi bosiljak",
    price: "3.90 €",
    category: "početak",
    sub_category: "juhe",
  },
  {
    name: "Ćevapi",
    description: "100% junetina, 7 kom (230g) / 10 kom (330g)",
    price: "6.80 € / 8.60 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Ćevapi sa sirom",
    description: "100% junetina, 7 kom (230g) / 10 kom (330g)",
    price: "7.90 € / 9.60 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Pileći ćevapi sa sirom",
    description: "7 kom (230g) / 10 kom (330g)",
    price: "7.70 € / 9.20 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Tri vrste ćevapa",
    description: "juneći ćevapi, juneći ćevapi sa sirom, pileći ćevapi 9 kom (300g)",
    price: "8.10 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Ćevapi u umaku od kajmaka",
    description: "100% junetina, 10 kom (330g)",
    price: "10.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Ćevapi u umaku od pečenih paprika",
    description: "100% junetina, 10 kom (330g)",
    price: "10.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Gurmanski ćevapi",
    description:
      "2 kom junetina, svinjetina, sir, dimljena slanina, pikantna papričica, papar, krem umak od pečene paprike, pikantni feferoni",
    price: "8.10 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Pileći batak i zabatak",
    description: "1 kom / 2 kom očišćeni od kosti",
    price: "5.20 € / 9.40 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Mesni uštipci",
    description:
      "junetina, svinjetina, sir, dimljena slanina, tucana paprika, slatke rajčice 5 kom (300g)",
    price: "9.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Gurmanska pljeskavica",
    description:
      "junetina, svinjetina, sir, dimljena slanina, tucana paprika, kajmak, pikantni feferoni (330g)",
    price: "10.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Punjena vješalica",
    description: "1 kom / 2 kom svinjski kare punjen sirom i omotan dimljenom slaninom",
    price: "7.30 € / 12.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Punjena vješalica u umaku od kajmaka",
    description:
      "Svinjski kare punjen sirom, omotan dimljenom slaninom, umak od kajmaka, 2 kom",
    price: "13.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Punjeni pileći batak zabatak",
    description:
      "Očišćeni pileći batak i zabatak, punjen delikates šunkom, sirom i kajmakom, omotan dimljenom slaninom (390g)",
    price: "11.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "BBQ krilca",
    description: "pileća krilca sa grilla, BBQ umak",
    price: "9.20 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "BBQ rebarca",
    description: "BBQ rebarca svinjetina, BBQ umak",
    price: "14.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Plata Batak (za 2 osobe)",
    description:
      "juneći ćevapi sa sirom, pileći ćevapi, punjena vješalica, batak zabatak, krške mladog krumpira, šampinjoni, kajmak",
    price: "36.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mješane plate",
  },
  {
    name: "Gurmanska plata (za 2 osobe)",
    description:
      "juneći ćevapi sa sirom, gurmanska pljeskavica, punjena vješalica, uštipci, krške mladog krumpira, šampinjoni, umbeš",
    price: "36.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mješane plate",
  },
  {
    name: "Batak burger",
    description:
      "100% junetina, brioche pecivo, cheddar sir, iceberg salata, rajčica, pržena slanina, blagi ili ljuti umak",
    price: "8.70 €",
    category: "glavna jela / roštilj",
    sub_category: "burgeri",
  },
  {
    name: "Batak burger special",
    description:
      "100% junetina, brioche pecivo, grillani Tomino sir, iceberg salata, rajčica, pržena slanina, blagi ili ljuti umak",
    price: "11.50 €",
    category: "glavna jela / roštilj",
    sub_category: "burgeri",
  },
  {
    name: "Rib-Eye steak",
    description: "dry aged Black Angus, cca. 300g",
    price: "7.70 € / 10.90 €",
    category: "glavna jela / roštilj",
    sub_category: "steakovi",
  },
  {
    name: "Zagrebački odrezak",
    description: "pileći file punjen delikates šunkom i sirom, paniran u panko mrvicama",
    price: "11.50 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Čobanac",
    description: "junetina, svinjetina, domaće njoke, ½ lepinja",
    price: "9.90 €",
    category: "glavna jela / roštilj",
    sub_category: "mesna jela",
  },
  {
    name: "Losos file",
    description: "File lososa sa žara, blitva s krumpirom",
    price: "14.20 €",
    category: "glavna jela / roštilj",
    sub_category: "riba",
  },
  {
    name: "Toplo hladna salata s grillanom piletinom",
    description:
      "očišćeni pileći batak zabatak, zelena salata, miješane mlade salate, feta sir, polu sušene rajčice, pržena slanina, krutoni dressing po izboru: jogurt-med-senf/aceto-maslinovo ulje",
    price: "10.20 €",
    category: "glavna jela / roštilj",
    sub_category: "salate",
  },
  {
    name: "Losos salata",
    description:
      "pečene kockice lososa, iceberg salata, rukola, svježi krastavci u umaku od jogurta i kopra, rotkvice, maslinovo ulje",
    price: "14.20 €",
    category: "glavna jela / roštilj",
    sub_category: "salate",
  },
  {
    name: "Lepinja",
    description: "1 kom",
    price: "1.60 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Pommes Frites",
    description: "150g",
    price: "3.00 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Kriške mladog krumpira",
    description: "sa topljenim sirom i prženim komadićima slanine",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Domaći krumpir",
    description: "sa topljenim sirom i prženim komadićima slanine",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Pommes frites od batata",
    description: "",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Blitva s krumpirom",
    description: "",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Zapečeni grah",
    description: "",
    price: "4.00 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Šampinjoni sa žara",
    description: "",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Povrće sa žara",
    description: "",
    price: "4.00 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Zapečena paprika",
    description: "u krem umaku od vrhnja s grana padano sirom",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Feferoni sa žara",
    description: "",
    price: "4.30 €",
    category: "prilozi i salate",
    sub_category: "prilozi",
  },
  {
    name: "Kupus / zelena / rajčica / krastavac",
    description: "",
    price: "3.20 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Miješana salata",
    description: "",
    price: "3.60 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Rikula",
    description: "",
    price: "3.80 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Rikula s cherry rajčicama",
    description: "",
    price: "4.00 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Cherry rajčice",
    description: "",
    price: "3.20 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Pečena crvena paprika",
    description: "",
    price: "3.60 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Coleslaw salata",
    description: "kupus, mrkva, celer, dressing",
    price: "3.00 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Šopska salata",
    description: "rajčica, paprika, krastavac, luk, feta sir",
    price: "4.20 €",
    category: "prilozi i salate",
    sub_category: "salate",
  },
  {
    name: "Umak od kajmaka",
    description: "",
    price: "2.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Kajmak / Umbeš",
    description: "",
    price: "2.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Batak BBQ umak",
    description: "",
    price: "1.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Jalapeno papričice",
    description: "",
    price: "1.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Ajvar domaći",
    description: "",
    price: "2.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Krem umak od pečenih paprika",
    description: "",
    price: "2.50 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Kren / Ketchup / Senf / Majoneza / Tartar",
    description: "",
    price: "1.00 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Dressing za salatu",
    description: "jogurt / med / senf 1 kom",
    price: "1.00 €",
    category: "prilozi i salate",
    sub_category: "dodaci",
  },
  {
    name: "Ćevapi mini",
    description: "Ćevapi (junetina) 5 kom, pomfrit, ketchup",
    price: "6.90 €",
    category: "dječji menu",
    sub_category: "dječji menu",
  },
  {
    name: "Batak mini",
    description: "pohani prženi batak zabatak u panko mrvicama, pomfrit, ketchup",
    price: "7.30 €",
    category: "dječji menu",
    sub_category: "dječji menu",
  },
];
